title:            malczak.net
description:      "Developer's point of view."
logo:             logo.png
disqus_shortname: blogmalczaknet
share:            false
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:        	  http://localhost:4000

# Owner/author information
owner:
  name:           Jakub Malczak
  avatar:         jm.jpg
  email:          jmalczak@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Software Developer
  # Social networking links used in footer. Update and remove as you like.
  twitter:        malczu
  facebook:       malczu
  github:         jmalczak
  linkedin:       jakubmalczak

# Analytics and webmaster tools stuff goes here
google_analytics: UA-12734243-1

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Warsaw
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

include: [".htaccess"]
